### ISSUE TITLE
Add Pure K8s Manifests

### ISSUE THREAD

**Issue by christopherhein** [aws-samples/aws-compute-options#12]
Add a pure k8s manifest directory `app/k8s` to show more examples of deployment models.

**Original Question:**
> Should we have a directory under `apps/` that has the manifest files un-templatized? Thinking so that we can support all kinds of deployments `w/ helm` `pure k8s`, `w/ docker`, `w/ fargate`, `w/ ecs` etc?

**Comment by arun-gupta** [comment]
Use `helm install --dry-run --debug` to generate pure k8s manifest files?

**Comment by christopherhein** [comment]
Yeah, that would work, I think you have to prune the output a bit for it to be completely valid. For example that will return

```bash
→ helm install --dry-run --debug myapp
[debug] Created tunnel using local port: '56146'

[debug] SERVER: "127.0.0.1:56146"

[debug] Original chart version: ""
[debug] CHART PATH: /Users/heichris/Code/src/github.com/christopherhein/aws-compute-options/apps/k8s/myapp

NAME:   busted-pig
REVISION: 1
RELEASED: Mon Feb 19 14:53:49 2018
CHART: app-0.1.0
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
greeting:
  image: arungupta/greeting
  replicaCount: 1
name:
  image: arungupta/name
  replicaCount: 1
webapp:
  image: arungupta/webapp
  replicaCount: 1

HOOKS:
MANIFEST:

---
# Source: app/templates/greeting-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: busted-pig-greeting
  labels:
    name: busted-pig-greeting
  labels:
    generator: helm
    date: 2018-02-19
    release: busted-pig
    revision: "1"
    chart: app
    version: 0.1.0
spec:
  selector:
    app: busted-pig-greeting
  ports:
  - name: http
    protocol: TCP
    port: 8081
#...
```

Which you can't just pipe into a file and install with. I'm thinking more along the lines of a single `manifest.yml` in `apps/k8s/standalone` (or some path similar) where if they didn't even want to install `helm` they could `kubectl apply -f manifest.yml`

Thoughts?

**Comment by arun-gupta** [comment]
`kubectl apply` would be definitely beneficial. Do you want to file an issue to get that created?

**Comment by christopherhein** [comment]
Yeah, I'm just going to switch this issue to that.
